version: 2.1

orbs:
  kaocha: lambdaisland/kaocha@0.0.1
  clojure: lambdaisland/clojure@0.0.4
  win: circleci/windows@2.2.0

jobs:
  test:
    parameters:
      os:
        type: executor
      clojure_version:
        type: string
    executor: << parameters.os >>
    steps:
      - checkout
      - clojure/with_cache:
          cache_version: << parameters.clojure_version >>
          steps:
            - run: clojure -e '(println (System/getProperty "java.runtime.name") (System/getProperty "java.runtime.version") "\nClojure" (clojure-version))'
            - kaocha/execute:
                args: "unit --reporter documentation --plugin cloverage --codecov"
                clojure_version: << parameters.clojure_version >>
            - kaocha/upload_codecov:
                flags: unit
            - kaocha/execute:
                args: "integration --reporter documentation --plugin cloverage --codecov"
                clojure_version: << parameters.clojure_version >>
      - kaocha/upload_codecov:
          flags: integration
          file: target/coverage/integration*/codecov.json
  windows-test:
    executor:
      name: win/default
    steps:
      - run:
          command: $(echo hello | Out-Host; $?) -and $(echo world | Out-Host; $?)
          shell: powershell.exe
      - run:
          command: Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://download.clojure.org/install/win-install-1.10.3.839.ps1')
          shell: powershell.exe

workflows:
  kaocha_test:
    jobs:
      - test:
          matrix:
            parameters:
              os: [clojure/openjdk16, clojure/openjdk15, clojure/openjdk11, clojure/openjdk8]
              clojure_version: ["1.9.0", "1.10.1"]

      - windows-test


