version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:9
    steps:
      - checkout
      - run: curl -O https://download.clojure.org/install/linux-install-1.9.0.375.sh
      - run: chmod +x linux-install-1.9.0.375.sh
      - run: sudo ./linux-install-1.9.0.375.sh
      - run: clojure -A:test
