version: 2.1

orbs:
  kaocha: lambdaisland/kaocha@dev:first
  clojure: lambdaisland/clojure@dev:first

commands:
  checkout_and_run:
    parameters:
      clojure_version:
        type: string
    steps:
      - checkout
      - clojure/with_cache:
          cache_version: << parameters.clojure_version >>
          steps:
            - run: clojure -e '(println (System/getProperty "java.runtime.name") (System/getProperty "java.runtime.version") "\nClojure" (clojure-version))'
            - kaocha/execute:
                args: "unit --reporter documentation --plugin cloverage --codecov"
                clojure_version: << parameters.clojure_version >>
            - kaocha/execute:
                args: "integration --reporter documentation --plugin cloverage --codecov"
                clojure_version: << parameters.clojure_version >>
      - kaocha/upload_codecov:
          flags: unit
      - kaocha/upload_codecov:
          flags: integration
          file: target/coverage/integration*/codecov.json

jobs:
  java-11-clojure-1_10:
    executor: clojure/openjdk11
    steps: [{checkout_and_run: {clojure_version: "1.10.0-RC2"}}]

  java-11-clojure-1_8:
    executor: clojure/openjdk11
    steps: [{checkout_and_run: {clojure_version: "1.8.0"}}]

  java-9-clojure-1_9:
    executor: clojure/openjdk9
    steps: [{checkout_and_run: {clojure_version: "1.9.0"}}]

  java-8-clojure-1_8:
    executor: clojure/openjdk8
    steps: [{checkout_and_run: {clojure_version: "1.8.0"}}]

  java-8-clojure-1_10:
    executor: clojure/openjdk8
    steps: [{checkout_and_run: {clojure_version: "1.10.0-RC2"}}]

workflows:
  kaocha_test:
    jobs:
      - java-11-clojure-1_8
      - java-11-clojure-1_10
      - java-9-clojure-1_9
      - java-8-clojure-1_8
      - java-8-clojure-1_10
